### ISSUE TITLE
Is there a way I can consume your API?

### ISSUE THREAD

**Issue by serhiiminin** [cara-care/dashboard#80]
## Summary
Hey! 
I am using your mobile app. It is amazing! Thank you for what you are doing.
I was looking for Cara Care API documentation on the Internet, but I haven't found it. 
When I share my tracking data by visiting the URL which is generated by the app, I can see this request in my network tab
`https://web.gohidoc.com/api/dashboard/me/data-points/?start=2021-12-05&end=2021-12-11&limit=100&offset=0`
It returns me an array of this kind of data
```
{
    "type": "stool",
    "value": 57,
    "text": null,
    "timestampTracking": "2021-11-29T08:57:36.470000Z",
    "timestampEntry": "2021-11-29T08:57:41.553000Z",
    "timestampLastModified": "2021-11-29T08:57:41.553000Z",
    "userDateTracking": "2021-11-29"
},
```
But in order to know what `"value": 57` means I need to make one more request to get the list of possible values and maybe some more requests.

I need it for my personal purposes, nothing commercial, just to analyze the information in a way I want it, to do some monthly report for myself. 
Is there such a possibility?

**Comment by pavelsof** [comment]
Thank you very much for the nice words! :pray: 

The backend API is somewhat documented in the project's [GitHub wiki](https://github.com/cara-care/dashboard/wiki) (e.g. [this page](https://github.com/cara-care/dashboard/wiki/Tracking-data) would include a bit of info about the endpoint). However, you are right, the wiki does not mention that the tracking data points of type "stool" use the following hardcoded integer values:

- 0 → no stool
- 14 → type 1
- 28 → type 2
- 42 → type 3
- 57 → type 4
- 71 → type 5
- 85 → type 6
- 100 → type 7

...where the types 1-7 refer to the [Bristol stool scale](https://en.wikipedia.org/wiki/Bristol_stool_scale) types. At the moment there is no endpoint which handles the conversion from integer values to categorical data, so I would suggest you to also hardcode them – not exactly an elegant solution, but it should work fine :upside_down_face:

**Comment by serhiiminin** [comment]
> so I would suggest you to also hardcode them – not exactly an elegant solution, but it should work fine

In this case, I will need to hardcode not only stool values but everything else (e.g. food, workout, etc.) 
So I can find all of them on the wiki page?
And BTW, `user_id` in this kind of endpoint `/dashboard/<user_id: int>/` is a randomly generated id that is stored in the database, or it is a username that I can see when I log in to the app?

**Comment by pavelsof** [comment]
The tracking data points of type "food" have non-empty lists of `mealItems`, which in turn would include either a non-empty list of `foodItems` or `customFoodItems` (or both). Most of the tracking data point types store their value in the `value` field, which, if not null, would be an integer in the range `[0; 100]`.

The endpoints available to end users are a small subset of the endpoints available to nutritionist users. When the endpoint is available, you can substitute the integer ID with "me" – so, the endpoint for retrieving the tracking data points would be `GET /dashboard/me/data-points/` (as you have already found out).

**Comment by serhiiminin** [comment]
Thank you for the detailed explanation!

**Comment by pavelsof** [comment]
You are welcome! :pray: 
...and sorry for the lack of proper documentation!
